model_params:
  name: 'VQ_VAE'
  in_channels: 3
  embedding_dim: 64
  num_embeddings: 512
  img_size: 64
  beta: 0.25

data_params:
  data_path: "/home/sunp/vae/dataset/images"
  train_batch_size: 256
  val_batch_size:  256
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.0001
  weight_decay: 0.0
  scheduler_gamma: 0.0
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  devices: [1]
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: 'VQVAE'